# Generated by Django 3.0.2 on 2020-01-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrarAnime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_anime', models.CharField(max_length=50, verbose_name='Nome Anime')),
                ('temporada', models.CharField(max_length=50, verbose_name='Temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('telefone_1', models.CharField(max_length=11, verbose_name='Telefone Principal')),
                ('telefone_2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone Secundario')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
