# Generated by Django 3.0.2 on 2020-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrarGastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome Produto')),
                ('valor', models.CharField(max_length=11, verbose_name='Valor')),
                ('parcela', models.CharField(max_length=11, verbose_name='Parcelas')),
                ('comentario', models.CharField(max_length=11, verbose_name='Comentario')),
            ],
        ),
    ]
